Repository openvpi/LabelVoice, pull requests merged in 2022-10, with the labels that each got.

#5 Add specification
  README.md
  docs/spec.zh-CN.md
Labels: documentation

#6 Add audio playback and demo
  .gitignore
  README.md
  src/.gitignore
  src/LabelVoice.Core/Audio/AudioBackend.cs
  src/LabelVoice.Core/Audio/AudioDecoder.cs
  src/LabelVoice.Core/Audio/AudioDevice.cs
  src/LabelVoice.Core/Audio/FFmpegAudioDecoder.cs
  src/LabelVoice.Core/Audio/IAudioPlayback.cs
  src/LabelVoice.Core/Audio/NAudioDecoder.cs
  src/LabelVoice.Core/Audio/NAudioPlayback.cs
  src/LabelVoice.Core/Audio/PortAudio/PaAudioDevice.cs
  src/LabelVoice.Core/Audio/PortAudio/PaAudioEngine.cs
  src/LabelVoice.Core/Audio/PortAudio/PaAudioFrame.cs
  src/LabelVoice.Core/Audio/PortAudio/PaBinding.Delegates.cs
  src/LabelVoice.Core/Audio/PortAudio/PaBinding.Enums.cs
  src/LabelVoice.Core/Audio/PortAudio/PaBinding.Structs.cs
  src/LabelVoice.Core/Audio/PortAudio/PaBinding.cs
  src/LabelVoice.Core/Audio/PortAudioPlayback.cs
  src/LabelVoice.Core/Audio/SDLPlayback.cs
  src/LabelVoice.Core/Audio/SDLPlaybackImpl/SDLGlobal.cs
  src/LabelVoice.Core/Audio/SDLPlaybackImpl/SDLHost.cs
  src/LabelVoice.Core/Audio/SDLPlaybackImpl/SDLPlaybackData.cs
  src/LabelVoice.Core/Audio/SDLPlaybackImpl/SDLReimpl.cs
  src/LabelVoice.Core/Audio/SineGen.cs
  src/LabelVoice.Core/LabelVoice.Core.csproj
  src/LabelVoice.Core/Managers/PlaybackManager.cs
  src/LabelVoice/App.axaml.cs
  src/LabelVoice/LabelVoice.csproj
  src/LabelVoice/ViewModels/AudioPlayerWindowViewModel.cs
  src/LabelVoice/Views/AudioPlayerWindow.axaml
  src/LabelVoice/Views/AudioPlayerWindow.axaml.cs
Labels: enhancement, feature

#10 Add model classes
  docs/spec.zh-CN.md
  src/LabelVoice.Core/LabelVoice.Core.csproj
  src/LabelVoice.Core/Managers/ProjectManager.cs
  src/LabelVoice.Core/Models/LabelVoiceItem.cs
  src/LabelVoice.Core/Models/LabelVoiceProject.cs
  src/LabelVoice.Core/Models/LabelVoiceText.cs
  src/LabelVoice.Core/Models/ValueType.cs
  src/LabelVoice.Core/ProjectModel/LvProject.cs
  src/LabelVoice.Core/Utils/HexCodeGenerator.cs
  src/LabelVoice.Core/Utils/VirtualPathValidator.cs
  src/LabelVoice/LabelVoice.csproj
  src/LabelVoice/Views/MainWindow.axaml.cs
Labels: feature

#9 NavigatorView for visualizing items and slices
  src/LabelVoice.Widgets/.gitignore
  src/LabelVoice.Widgets/App.axaml
  src/LabelVoice.Widgets/App.axaml.cs
  src/LabelVoice.Widgets/Core/Types.cs
  src/LabelVoice.Widgets/LabelVoice.Widgets.csproj
  src/LabelVoice.Widgets/Program.cs
  src/LabelVoice.Widgets/ViewLocator.cs
  src/LabelVoice.Widgets/ViewModels/MainWindowViewModel.cs
  src/LabelVoice.Widgets/ViewModels/ViewModelBase.cs
  src/LabelVoice.Widgets/Views/DockBar.axaml
  src/LabelVoice.Widgets/Views/DockBar.axaml.cs
  src/LabelVoice.Widgets/Views/DockCard.axaml
  src/LabelVoice.Widgets/Views/DockCard.axaml.cs
  src/LabelVoice.Widgets/Views/DockWidget.axaml
  src/LabelVoice.Widgets/Views/DockWidget.axaml.cs
  src/LabelVoice.Widgets/Views/MainWindow.axaml
  src/LabelVoice.Widgets/Views/MainWindow.axaml.cs
  src/LabelVoice.sln
  src/LabelVoice/App.axaml.cs
  src/LabelVoice/LabelVoice.csproj
  src/LabelVoice/Styles/Fonts.Win.axaml
  src/LabelVoice/ViewModels/ItemsTreeItemViewModel.cs
  src/LabelVoice/ViewModels/MainWindowViewModel.cs
  src/LabelVoice/ViewModels/SlicesListItemViewModel.cs
  src/LabelVoice/Views/ContextMenuItem.axaml
  src/LabelVoice/Views/ContextMenuItem.axaml.cs
  src/LabelVoice/Views/ItemsPanel.axaml
  src/LabelVoice/Views/ItemsPanel.axaml.cs
  src/LabelVoice/Views/ItemsTreeItem.axaml
  src/LabelVoice/Views/ItemsTreeItem.axaml.cs
  src/LabelVoice/Views/MainWindow.axaml
  src/LabelVoice/Views/MainWindow.axaml.cs
  src/LabelVoice/Views/SlicesListItem.axaml
  src/LabelVoice/Views/SlicesListItem.axaml.cs
  src/LabelVoice/Views/SlicesPanel.axaml
  src/LabelVoice/Views/SlicesPanel.axaml.cs
  src/LabelVoice/Views/TypeInDialog.axaml
  src/LabelVoice/Views/TypeInDialog.axaml.cs
  src/Test.Playback/Converter.cs
  src/Test.Playback/Program.cs
  src/Test.Playback/Test.Playback.csproj
Labels: feature
